name: Package

on:
  workflow_dispatch: {}

jobs:
  macos-build:
    runs-on: macos-11.1
    steps:
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install NumPy
        run: pip install --no-cache-dir --user numpy

      - name: Build libmediapipe_c.dylib
        run: |
          unset ANDROID_NDK_HOME
          python build.py build --desktop cpu --opencv cmake -vv
      - name: Upload libmediapipe_c.dylib
        uses: actions/upload-artifact@v2
        with:
          name: libmediapipe_c.dylib
          path: Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib
